version: "2"
    
services:
   # MySQL DB
  db:
    build: ./MySQL
    ports:
      - "8080:3306"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    environment:
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
    restart: always
    networks:
      - wpsite
  # WordPress
  wordpress:
    build: ./WordPress
    depends_on:
      - db
    ports:
      - '80:80'
    restart: always
    volumes:
      - type: volume
        source: wordpress_data
        target: /etc/wordpress
      - type: volume
        source: wpuploads
        target: /var/www/html/wp-content/uploads
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  mysql_data: {}
  wordpress_data: {}
  wpuploads: {}