version: "2"
    
services:
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DB: wordpress
      MYSQL_USER: lab3
      MYSQL_PASSWORD: lab31234567
    
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB: wordpress
      WORDPRESS_DB_USER: lab3
      WORDPRESS_DB_PASS: lab31234567
volumes:
  mysql_data: {}
  wordpress_data: {}