version: "1"

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: wordpress
      MYSQL_USER: lab3
      MYSQL_PASSWORD: lab31234567

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: lab3
      WORDPRESS_DB_PASSWORD: lab31234567
volumes:
  mysql_data: {}
  wordpress_data: {}
